name: Debug
on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  debug:
    name: Debug
    runs-on: windows-latest

    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: true
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
      DOTNET_NOLOGO: true

    steps:
      - uses: actions/checkout@v3

      - name: ls
        run: |
            ls -la $GITHUB_WORKSPACE
